name: Deploy to server

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.4.0
            - name: Pull
              uses: garygrossgarten/github-action-ssh@v0.6.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  password: ${{ secrets.PASSWORD }}
                  command: cd ${{ secrets.FOLDER }} && git pull
